import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import HeaderMain from "@/components/HeaderMain";
import Home from "./page";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme={"cupcake" || "dark"}>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <div className="flex-grow">
            <div className="container mx-auto">
              <Header />
              <HeaderMain />
              <NavBar />
              {children}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
